import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game/simulation.ts';
import {defaultProfile,decodeSave} from '../src/game/save.ts';
import {createChronicle} from '../src/game/chronicle.ts';
function ready(){const p=defaultProfile();p.unlocked=[true,true,true];p.chronicle=createChronicle();return new Game(p);}
test('version five migrates version four without losing cards or selected legacy',()=>{const p={...defaultProfile(),version:4 as const,chronicle:undefined,legacy:{rank:2 as const,selected:'watch' as const}};p.cards[0]=12;const clean=decodeSave(JSON.stringify(p));assert.equal(clean.profile?.version,5);assert.equal(clean.profile?.legacy.selected,'watch');assert.equal(clean.profile?.legacy.rank,2);assert.equal(clean.profile?.cards[0],12);assert.equal(clean.profile?.chronicle?.route,'road');});
test('unknown outer and nested future versions remain protected',()=>{assert.equal(decodeSave(JSON.stringify({...defaultProfile(),version:99})).problem,'unsupported');assert.equal(decodeSave(JSON.stringify({...defaultProfile(),chronicle:{version:2}})).problem,'unsupported');});
test('real Game rally holds a newly deployed company and releases it',()=>{const game=ready();assert.equal(game.dispatch({type:'rally'}),false);game.dispatch({type:'start'});game.dispatch({type:'rally'});assert.equal(game.dispatch({type:'spawn',kind:0}),true);for(let i=0;i<300;i++)game.step(1/60);assert.ok(game.state.units.find(u=>u.side==='player')!.x<=240);assert.equal(game.dispatch({type:'rally'}),true);for(let i=0;i<60;i++)game.step(1/60);assert.ok(game.state.units.find(u=>u.side==='player')!.x>240);});
test('replacing Food Drop remains usable at full food and consumes exactly once',()=>{const game=ready();assert.equal(game.dispatch({type:'chronicle-captain',captain:'gatekeeper'}),true);game.dispatch({type:'start'});game.state.food=99;assert.equal(game.canUseSkill('food'),true);assert.equal(game.dispatch({type:'skill',skill:'food'}),true);assert.equal(game.state.food,99);assert.equal(game.state.chronicle!.shieldUntil,6);assert.equal(game.dispatch({type:'skill',skill:'food'}),false);});
test('escort settles through the real victory pipeline only when the cart arrives',()=>{const game=ready();game.dispatch({type:'chronicle-route',route:'escort',battle:0});game.dispatch({type:'start'});game.state.enemyHp=0;game.step(1/60);assert.equal(game.state.phase,'running');game.state.chronicle!.cart.x=790;game.step(1/60);assert.equal(game.state.phase,'won');assert.equal(game.profile.chronicle!.choices[0],'cart');assert.ok(game.profile.pendingVictory);const wins=game.profile.wins;const story=JSON.stringify(game.profile.chronicle);for(let i=0;i<20;i++)game.step(.25);assert.equal(game.profile.wins,wins);assert.equal(JSON.stringify(game.profile.chronicle),story);const reload=new Game(game.profile);assert.equal(reload.state.phase,'won');assert.equal(JSON.stringify(reload.profile.chronicle),story);});
test('expedition checkpoint survives reload and cannot be skipped through legacy next',()=>{const game=ready();game.profile.chronicle!.restoration=1;assert.equal(game.dispatch({type:'chronicle-expedition',battle:0}),true);game.dispatch({type:'start'});game.state.chronicle!.cart.x=790;game.step(1/60);const resumed=new Game(game.profile);assert.equal(resumed.state.phase,'won');assert.equal(resumed.profile.chronicle!.expedition?.stage,0);assert.equal(resumed.dispatch({type:'next'}),false);assert.equal(resumed.dispatch({type:'chronicle-continue'}),true);assert.equal(resumed.state.phase,'ready');assert.equal(resumed.profile.pendingVictory,null);assert.equal(resumed.profile.chronicle!.expedition?.stage,1);assert.equal(resumed.dispatch({type:'chronicle-continue'}),false);});
test('a lost escort keeps gate health and does not award a victory',()=>{const game=ready();game.dispatch({type:'chronicle-route',route:'escort',battle:0});game.dispatch({type:'start'});game.state.chronicle!.cart.hp=0;game.step(1/60);assert.equal(game.state.phase,'lost');assert.ok(game.state.playerHp>0);assert.equal(game.profile.wins,0);assert.equal(game.profile.pendingVictory,null);});
test('old save cannot inject a locked expedition chapter',()=>{const p=defaultProfile();p.chronicle=createChronicle();p.chronicle.expedition={stage:2,chapter:5,reserve:12,provision:'shelter'};const clean=decodeSave(JSON.stringify(p)).profile!;assert.equal(clean.chronicle!.expedition,null);assert.equal(clean.enemyAge,0);});
test('an escort victory preserves the unbroken opposing gate and route receipt across reload',()=>{const game=ready();game.dispatch({type:'chronicle-route',route:'escort',battle:0});game.dispatch({type:'start'});const enemyHp=game.state.enemyHp;game.state.chronicle!.cart.x=790;game.state.chronicle!.cart.hp=100;game.step(1/60);assert.equal(game.state.enemyHp,enemyHp);const reloaded=new Game(game.profile);assert.equal(reloaded.state.enemyHp,enemyHp);assert.equal(reloaded.state.chronicle!.cart.x,790);assert.equal(reloaded.state.chronicle!.cart.hp,100);assert.equal(reloaded.state.chronicle!.settled,true);});
