import { ROUTES, CAPTAINS, TALES, DISCOVERIES, createChronicle, routeAvailable, routeBit, routeDefinition, captainAvailable, taleAvailable, timelineVariant, commanderFor, veteranName, type ChronicleAction, type RouteId, type CaptainId, type TaleId, type Preparation, type DiscoveryId } from '../game/chronicle.ts';
import type {Profile,BattleState} from '../game/types.ts';
const chapters=['The first hearth','Olive terraces','The harbour','Lantern street','The hillside','Quiet courtyards'];
const landscapes=['/art/storybook/village.webp',...['olive','harbor','lantern','hillside','courtyards'].map(folder=>`/art/storybook/${folder}/village.webp`)];
const escape=(text:string)=>text.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const checked=(selected:boolean)=>`aria-pressed="${selected}"${selected?' class="chosen"':''}`;
const number=(value:string|undefined)=>value!==undefined&&/^[0-5]$/.test(value)?Number(value):null;
/** DOM input is untrusted even though these controls are authored by us. */
export function chronicleActionFromData(data:Record<string,string|undefined>):ChronicleAction|null {
  if(data.storyRoute&&ROUTES.some(r=>r.id===data.storyRoute)){const battle=number(data.storyBattle);return battle===null?null:{type:'chronicle-route',route:data.storyRoute as RouteId,battle};}
  if(data.storyCaptain&&CAPTAINS.some(c=>c.id===data.storyCaptain))return {type:'chronicle-captain',captain:data.storyCaptain as CaptainId};
  if(data.storyTale&&TALES.some(t=>t.id===data.storyTale))return {type:'chronicle-tale',tale:data.storyTale as TaleId};
  if(data.storyPreparation&&['none','bread','repair'].includes(data.storyPreparation))return {type:'chronicle-preparation',preparation:data.storyPreparation as Preparation};
  if(data.storyDiscovery&&DISCOVERIES.some(d=>d.id===data.storyDiscovery))return {type:'chronicle-discover',discovery:data.storyDiscovery as DiscoveryId};
  if(data.storyProvision==='supplies'||data.storyProvision==='shelter')return {type:'chronicle-provision',provision:data.storyProvision};
  if(data.command==='story-expedition'){const battle=number(data.storyBattle);return battle===null?null:{type:'chronicle-expedition',battle};}
  if(data.command==='story-continue')return {type:'chronicle-continue'};
  if(data.command==='story-abandon')return {type:'chronicle-abandon'};
  if(data.command==='story-rally')return {type:'rally'};
  return null;
}
export function chronicleScreenHtml(p:Profile,s:BattleState,page=p.enemyAge):string {
  const c=p.chronicle??createChronicle(p.timeline,p.enemyAge),chapter=Number.isInteger(page)&&page>=0&&page<=p.furthestBattle?page:p.enemyAge,variant=timelineVariant(p.timeline),persona=commanderFor(c,chapter),busy=s.phase==='running';
  const routeMap=ROUTES.map((route,index)=>{
    const available=!busy&&routeAvailable(c,route.id,chapter,p.furthestBattle)&&!c.expedition,done=(c.clears[chapter]&routeBit(route.id))!==0;
    return `<button class="story-route route-${index}${c.chapter===chapter&&c.route===route.id?' selected':''}" data-story-route="${route.id}" data-story-battle="${chapter}" ${available?'':'disabled'} aria-label="${escape(`${route.name}. ${route.rule}${done?' Already completed.':''}${available?'':' Finish another route to reveal this path.'}`)}"><small>${done?'A TOLD TALE':route.objective.toUpperCase()}</small><strong>${escape(route.name)}</strong><span>${escape(route.rule)}</span></button>`;
  }).join('');
  const houses=[{bit:1,name:'The oven',copy:'Bread adds three starting food.',preparation:'bread'},{bit:2,name:'The courtyard',copy:'Neighbours return; Younes joins the company.',preparation:''},{bit:4,name:'The workshop',copy:'Repairs add 15% starting gate health.',preparation:'repair'}];
  const settlement=houses.map(h=>`<div class="story-house ${(c.restoration&h.bit)?'restored':'sleeping'}"><span class="house-roof" aria-hidden="true"></span><span class="house-window" aria-hidden="true"></span><strong>${h.name}</strong><small>${(c.restoration&h.bit)?h.copy:({1:'Tell one new tale.',2:'Tell three different tales.',4:'Tell six different tales.'}[h.bit])}</small>${h.preparation&&(c.restoration&h.bit)?`<button data-story-preparation="${h.preparation}" ${checked(c.preparation===h.preparation)} ${busy?'disabled':''}>${c.preparation===h.preparation?'Prepared':'Prepare'}</button>`:''}</div>`).join('');
  return `<div class="chronicle-book"><header class="story-heading"><span class="eyebrow">A COMPANY OF NEIGHBOURS</span><h2 id="dialog-title">The unwritten road</h2><p>${escape(variant.name)} · ${escape(variant.description)}</p></header>
    <div class="story-chapters" aria-label="Storybook chapters">${chapters.map((name,i)=>`<button data-story-page="${i}" aria-label="${escape(name)}" aria-pressed="${chapter===i}" ${i>p.furthestBattle?'disabled':''}>${i+1}</button>`).join('')}</div>
    <section class="story-map" aria-label="Routes through ${escape(chapters[chapter])}"><div class="story-illustration" style="--story-landscape:url('${landscapes[chapter]}')"><span class="story-chapter-name">${escape(chapters[chapter])}</span><span class="story-map-lantern" aria-hidden="true"></span></div><div class="story-roads">${routeMap}</div></section>
    <p class="story-opponent"><strong>${escape(persona.name)}</strong> — ${escape(persona.description)}</p>
    ${c.choices[chapter]!=='none'?`<p class="story-consequence">${c.choices[chapter]==='cart'?'The rescued cart leaves two extra provisions at the start of this chapter’s battles.':'The rescued scout gives one extra second of warning before the Bell Keeper rings.'}</p>`:'<p class="story-consequence">Your first cart or scout rescue changes the help you receive in this chapter.</p>'}
    <details class="story-company"><summary>Your company · one captain, one featured tale</summary><h3>Who keeps watch?</h3><div class="story-choices">${CAPTAINS.map(captain=>`<button data-story-captain="${captain.id}" ${checked(c.captain===captain.id)} ${busy||!captainAvailable(c,captain.id)?'disabled':''}><strong>${escape(captain.name)}</strong><span>${escape(captain.description)}</span>${captainAvailable(c,captain.id)?'':'<small>Rescue a scout or restore the courtyard.</small>'}</button>`).join('')}</div><h3>A tale to carry</h3><p>Collected cards keep all their bonuses. Only one featured tale changes your tactics.</p><div class="story-choices">${TALES.map(tale=>`<button data-story-tale="${tale.id}" ${checked(c.tale===tale.id)} ${busy||!taleAvailable(c,tale.id)?'disabled':''}><strong>${escape(tale.name)}</strong><span>${escape(tale.description)}</span>${taleAvailable(c,tale.id)?'':`<small>${tale.id==='olive-thread'?'Find all three hidden folktale fragments.':tale.id==='borrowed-bell'?'Tell three different tales.':'Restore the oven with your first victory.'}</small>`}</button>`).join('')}</div><div class="story-veterans">${c.veterans.map((wins,role)=>`<p><strong>${escape(veteranName(role,wins))}</strong><span>${wins} survived ${wins===1?'victory':'victories'} · ${wins>=3?'a patched company insignia':'still finding their courage'}</span></p>`).join('')}</div></details>
    <section class="story-home" aria-label="Your returning neighbours"><h3>The lights come home</h3><div class="story-houses">${settlement}</div>${c.preparation!=='none'?`<button class="story-link" data-story-preparation="none" ${busy?'disabled':''}>Travel without ${c.preparation==='bread'?'bread':'repairs'}</button>`:''}<p>No timers or upkeep. One preparation applies to each new battle.</p></section>
    <details class="story-expedition"><summary>The long way home · three encounters</summary><p>Escort the cart, hold the courtyard, then face the Bell Keeper. Up to twelve leftover food carries between encounters. Progress is saved between battles; an unfinished battle restarts without removing earned coins.</p>${c.expedition?`<p>Encounter ${c.expedition.stage+1}/3 · ${c.expedition.reserve} food in reserve.</p><button data-command="story-abandon" ${busy?'disabled':''}>Leave this expedition · keep permanent progress</button>`:`<button data-command="story-expedition" data-story-battle="${chapter}" ${busy||!c.restoration?'disabled':''}>${c.restoration?'Take the long way home':'First, tell one tale'}</button>`}</details>
    ${c.discoveries?`<details class="story-fragments"><summary>Pages found in the margins</summary>${DISCOVERIES.filter(d=>(c.discoveries&d.bit)!==0).map(d=>`<h3>${escape(d.name)}</h3><p>${escape(d.text)}</p>`).join('')}</details>`:''}
    <button class="big-button green" data-command="close">Return to the company</button></div>`;
}
export function chronicleResultHtml(p:Profile,s:BattleState):string {
  const c=p.chronicle;if(!c?.enabled)return '';
  const won=s.phase==='won',name=routeDefinition(c.route).name;
  const discoveries=won&&(c.clears[p.enemyAge]??0)!==0?`<details class="story-discoveries"><summary>Look around the quiet battlefield</summary><p>Three details wait in the illustration. Nothing essential is hidden here.</p><div class="story-discovery-scene">${DISCOVERIES.map(d=>`<button data-story-discovery="${d.id}" ${(c.discoveries&d.bit)?'disabled':''}>${escape(d.name)}${(c.discoveries&d.bit)?' · found':''}</button>`).join('')}</div>${DISCOVERIES.filter(d=>(c.discoveries&d.bit)!==0).map(d=>`<p><strong>${escape(d.name)}.</strong> ${escape(d.text)}</p>`).join('')}</details>`:'';
  const run=c.expedition;
  return `<section class="story-result"><h3>${escape(name)}</h3><p>${won?'Another light returns to the courtyard.':'The company will try another road. Your permanent progress stays.'}</p>${c.choices[p.enemyAge]!=='none'?`<p>${c.choices[p.enemyAge]==='cart'?'Your rescued cart supplies future encounters in this chapter.':'Your rescued scout watches the Bell Keeper’s preparations.'}</p>`:''}${discoveries}${run?`<div class="story-run-result"><strong>Encounter ${run.stage+1} of 3 · ${run.reserve} food carried</strong>${won?`${run.stage<2?`<p>Choose help for the next encounter.</p><div class="story-provisions"><button data-story-provision="supplies" ${checked(run.provision==='supplies')}>Two extra food</button><button data-story-provision="shelter" ${checked(run.provision==='shelter')}>Reinforce the gate</button></div>`:''}<button class="big-button green" data-command="story-continue">${run.stage===2?'Bring the company home':'Continue the expedition'}</button>`:''}<button class="story-link" data-command="story-abandon">Leave the expedition · keep earned progress</button></div>`:''}<button class="big-button secondary" data-command="chronicle">Open the storybook</button></section>`;
}
